CC=arm-none-eabi-
CFLAGS =-mcpu=cortex-m4 -g -gdwarf-2
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
AS = $(wildcard *.s)
ASOBJ = $(AS:.s=.o)
project_name= learn-in-depth-CortexM4

all:$(project_name).hex
	@echo "=====Everything is build====="
%.o : %.c 
	$(CC)gcc.exe  $(INCS) $(CFLAGS) -c $< -o $@

$(project_name).elf : $(OBJ) $(ASOBJ)
	$(CC)ld.exe -T Linker_Script.ld $(OBJ) $(ASOBJ) -o $@ -Map=Map_file.Map
	cp $(project_name).elf $(project_name).axf
$(project_name).hex : $(project_name).elf 
	$(CC)objcopy.exe -O binary $< $@
	
clean:
	rm main.o 
	rm startup.o 
	rm learn-in-depth-CortexM4.elf 
	rm learn-in-depth-CortexM4.hex
	rm learn-in-depth-CortexM4.axf
	@echo "Everything clean"